name: subjectteacherappointmentmvc
services:
  web:
    image: subjectteacherappointmentmvc-web
    ports:
        - 8080:8080
  db:
    image: subjectteacherappointmentmvc-db
    ports:
        - 1433:1433